local modpath = minetest.get_modpath(minetest.get_current_modname())

dofile(modpath .. "/config.lua")
dofile(modpath .. "/spawn_suppression.lua")
dofile(modpath .. "/food.lua")
dofile(modpath .. "/shearing.lua")
dofile(modpath .. "/milking.lua")
dofile(modpath .. "/horse_compat.lua")
dofile(modpath .. "/pig_compat.lua")
dofile(modpath .. "/wolf_compat.lua")
dofile(modpath .. "/dedupe.lua")
